# Delo z objekti

```{css, echo=FALSE}
#metode-za-nize pre {
  margin-left: 2em;
}
```

Gradivi za to poglavje sta

- https://automatetheboringstuff.com/2e/chapter6/ 
- poglavje `Nizi` v https://lusy.fri.uni-lj.si/ucbenik/book/1206/index.html

Uporabna je tudi dokumentacija za različne tipe https://docs.python.org/3/tutorial/datastructures.html

Metod za sezname in nize je veliko. Spodaj je naštetih nekaj najpogosteje uporabljanih. Celoten seznam je v uradni dokumentaciji: https://docs.python.org/3/library/stdtypes.html#string-methods

Ponavadi lahko z Googlom, najdemo metodo, ki jo potrebujemo, če opišemo, kaj želimo 
narediti (npr. s `python count characters in string` hitro najdemo `count()` in primere uporabe).

## Metode za nize

- `niz.count(znak)` vrne število pojavitev znaka v nizu
- `niz.index(znak)` vrne indeks, na katerem se znak prvič pojavi; če ne obstaja sproži napako
- `niz.replace(niz1, niz2)` vrne niz, kjer so podnizi enaki `niz1` zamenjani z `niz2`
- `niz.lower()` in `niz.upper()` vrne niz, kjer iz malih črk naredi velike ali obratno
- `niz.islower()` in `niz.isupper()` vrne True, če je niz iz samih malih črk oz. velikih črk
- `niz.strip()` vrne niz, kjer z leve in desne strani odstrani "whitespace characters" (presledki, tab, `\n`). Lahko podamo neobvezni argument, s katerim določimo, katere znake 
naj odstrani z leve in desne. Obstajata tudi metodi `.rstrip()` in `.lstrip()`, ki odstranjujeta le z leve in desne.
```{python}
print('    Hello, World    \n'.strip())
```
- `"locilo".join(seznam)` združi elemente seznama v niz in postavi `locilo` 
med posamezne elemente
```{python}
print('ABC'.join(['Moje', 'ime', 'je', 'Rok']))
```
- `niz.split(locilo)` vrne seznam, kjer so elementi posamezni deli niza, ki jih 
ločuje `locilo`. Privzeta vrednost za `locilo` je presledek.
```{python}
print("Moje ime je Rok.".split())
```

## Metode za sezname

- `sez.append(element)` doda element na konec seznama
- `sez.extend(sez2)` na konec seznama `sez` pristavi seznam `sez2`, na kratko `sez += sez2`
- `sez.insert(i, x)` na mesto z indeksom `i` vstavi element `x`
- `sez.remove(x)` iz seznama odstrani prvo pojavitev elementa `x`
- `sez.pop(i)` odstrani element na indeksu `i` in ga vrne; če `i` ne podamo je to zadnji element
- `sez.index(x)` vrne prvi indeks, na katerem se nahaja vrednost `x`
- `sez.count(x)` vrne število pojavitev `x` v seznamu
- `sez.sort(reverse=False)` uredi seznam po velikosti naraščajoče / abecedi; če podamo neobvezni argument `reverse=True`, bo seznam urejen v nasprotnem vrstnem redu

## Sortiranje seznamov

Za sortiranje lahko uporabimo funkcijo `sorted(seznam)`, ki vrne sortiran seznam ali pa metodo `seznam.sort()`, ki spremeni originalni seznam, tako, da je sortiran.

Obema funkcijama lahko podamo neobvezni argument `reversed=True`, ki seznam sortira v nasprotnem vrstnem redu. Podamo lahko tudi neobvezni argument `key=ime_funkcije`, s katerim podamo ime funkcije, ki sprejme elemente seznama in vrne tiste elemente, po katerih želimo seznam sortirati. Primer sortiranja po tretjem elementu nabora:

```{python}
def sortirna_funkcija(element_seznama):
    return element_seznama[2]

student_tuples = [
    ('john', 'A', 15),
    ('jane', 'B', 12),
    ('dave', 'B', 10),
]
print(sorted(student_tuples, key=sortirna_funkcija))
```

Sortiramo lahko tudi po več komponentah nabora, če v funkciji vrnemo nabor komponent, po katerih želimo sortirati. npr. funkcija z `return (element_seznama[1], element_seznama[2])` bi seznam najprej sortirala po drugem elementu nabora, nato pa še po tretjem (tisti elementi seznama, ki imajo enak drugi element nabora, bi bili sortirani še po tretjem).


Več o sortiranju v uradni dokumentaciji: https://docs.python.org/3/howto/sorting.html

## Drugi tipi

### Nabori

Nabori so urejeni in nespremenljivi. Definira se jih z običajnimi oklepaji `()`. Do elementov dostopamo z indeksi od 0 naprej, kot pri seznamih. Ne moremo dodati novih elementov. Glej tudi: https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences

Vrednosti v naborih lahko "odpakiramo" nazaj v spremenljivke. Nabor lahko odpakiramo v manj spremenljivk, kot je elementov nabora, če eni od spremenljivk pred ime dodamo `*`. V to spremenljivko se bo shranil seznam presežnih elementov.

```{python}
sadje = ("jabolko", "banana", "črešnje")
zeleno, rumeno, rdece = sadje
print(rdece, rumeno, zeleno)
```

### Množice

Množice niso urejene in so nespremenljive. Definira se jih z zavitimi oklepaji `{}`. Vrednosti v množici so unikatne (ne moremo dodati dveh enakih). Do elementov lahko dostopamo z zanko. Nove elemente lahko dodamo z `mnozica.add(element)`. Glej tudi: https://docs.python.org/3/tutorial/datastructures.html#sets

## Pretvarjanje med tipi

Spremenljivko `a` lahko pretvorimo v najpogosteje uporabljane tipe z:

- `int(a)` vrne celo število
- `float(a)` vrne decimalno število
- `str(a)` vrne niz
- `list(a)` vrne seznam
- `tuple(a)` vrne nabor
- `set(a)` vrne množico
