# Slovarji

Gradivi za to poglavje sta

- https://automatetheboringstuff.com/2e/chapter5/ 
- poglavje `Slovar` v https://lusy.fri.uni-lj.si/ucbenik/book/1212/index.html

## Osnovne operacije

### Dostopanje do vrednosti

Do vrednosti dostopamo podobno kot pri seznamih, le da namesto indeksov uporabimo ključe.

```{python}
s = {'a': 6, 'b': 'test', 123: True}
print(s['b'])
```

Če ključ ne obstaja pride do napake. Temu se lahko izognemo z metodo `get`

```{python}
s = {'a': 6, 'b': 'test', 123: True}
print(s.get('a'))
print(s.get('ž', 100000))
```

### Spreminjanje in dodajanje

```{python}
s = {'a': 6, 'b': 'test', 123: True}
s['a'] = 10
s['abcd'] = False
print(s)
```

Nov par ključ-vrednost dodamo tako kot piše v tretji vrstici zgornjega primera. Pri dodajanju ni pomembno, če ključ še ne obstaja v slovarju, ampak se neobstoječi ključ doda in njegova vrednost se nastavi na vrednost desno od enačaja.

### Brisanje

```{python}
s = {'a': 6, 'b': 'test', 123: True}
del s['a']
print(s)
```

## Metode na slovarjih

- `s.get(kljuc, privzeta_vrednost)` vrne vrednost, ki ustreza ključu `kljuc`, če ključ ne obstaja v slovarju vrne None; lahko podamo še neobvezni parameter `privzeta_vrednost`, ki jo vrne, če ključ ne obstaja; glej primer na vrhu strani
- `s.pop(kljuc)` iz slovarja odstrani par s ključem `kljuc` in vrne vrednost
- `s.update(s2)` k slovarju `s` doda pare slovarja `s2`
- `s.values()` za uporabo v zankah; vrne vrednosti v slovarju; s funkcijo `list` pretvorimo v seznam
- `s.keys()` za uporabo v zankah; vrne ključe v slovarju; s funkcijo `list` pretvorimo v seznam
- `s.items()` za uporabo v zankah; vrne nabore ključev in vrednosti; s funkcijo `list` pretvorimo v seznam

## Preverjanje vsebovanja

Kot pri seznamih in nizih uporabimo ključno besedo `in`.

```{python eval=FALSE}
s = {'a': 6, 'b': 'test', 123: True}
print('test' in s.values())
print('b' in s.keys())
print(('a', 6) in s.items())
```

```
## True
## True
## True
```

## Zanke

Zanka po vrednostih v slovarju.

```{python}
s = {'a': 6, 'b': 'test', 123: True}
for v in s.values():
	print(v)
```

Zanka po ključih v slovarju.

```{python}
s = {'a': 6, 'b': 'test', 123: True}
for k in s.keys(): # lahko tudi "for k in s:"
	print(k)
```

Zanka po parih v slovarju.

```{python}
s = {'a': 6, 'b': 'test', 123: True}
for kljuc, vrednost in s.items():
	print(kljuc, '->', vrednost)
```
