# This is a basic workflow to help you get started with Actions

name: Build site and commit to output branch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
<<<<<<< HEAD
=======
  
name: Quarto publish and commit
>>>>>>> 56e0950 (Starting move to Quarto.)

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - uses: r-lib/actions/setup-r@v2
      
      - uses: r-lib/actions/setup-renv@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install rmarkdown, bookdown, tinytex, reticulate
        run: |
          Rscript -e 'install.packages(c("rmarkdown","bookdown","tinytex","reticulate"))'
          Rscript -e 'tinytex::install_tinytex()'

      - uses: actions/checkout@v3
        with:
          ref: 'output'
          path: 'output'
=======
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: production
          path: output
>>>>>>> 56e0950 (Starting move to Quarto.)
        
      - name: Build
        run: |
          chmod +x ./_build.sh
          ./_build.sh

<<<<<<< HEAD
      - name: Commit to output branch
        uses: EndBug/add-and-commit@v9.1.2
        with:
          author_name: 'GH Actions deployment workflow'
          author_email: 'kontakt@rokuk.org'
          cwd: 'output'
          push: 'origin output --set-upstream --force'

=======
>>>>>>> 56e0950 (Starting move to Quarto.)
      - name: Upload artfacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@main
        with:
          name: output
          path: output
