# This is a basic workflow to help you get started with Actions

name: Quarto publish and commit to the production banch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
        
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
        
      - uses: actions/checkout@v4
        with:
          ref: 'production'
          path: 'output'
        
      - name: Commit to production branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GH Actions deployment workflow'
          author_email: 'kontakt@rokuk.org'
          cwd: 'output'
          push: 'origin production --set-upstream --force'
        
      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: output
          path: output
